FROM centos:7.9.2009
MAINTAINER Cxs1103

ENV JENKINS_EVERSION=2.313 \
    TOMCAT_VERSION=9.0.53 \
    GRADLE_EVERSION=7.1.1 \
    GRADLE_HOME=/usr/local/gradle \
    TOMCAT_HOME=/usr/local/tomcat

RUN yum install wget curl unzip iproute net-tools -y && \
    yum clean all && \
    rm -rf /var/cache/yum/*

COPY jdk-8u241-linux-x64.tar.gz /usr/local/

RUN tar -zxf /usr/local/jdk-8u241-linux-x64.tar.gz  -C /usr/local/ && \
    rm -rf /usr/local/jdk-8u241-linux-x64.tar.gz && \
    wget http://mirrors.ustc.edu.cn/apache/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    tar zxf apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    mv apache-tomcat-${TOMCAT_VERSION} ${TOMCAT_HOME} && \
    rm -rf apache-tomcat-${TOMCAT_VERSION}.tar.gz ${TOMCAT_HOME}/webapps/* && \
    mkdir ${TOMCAT_HOME}/webapps/test && \
    sed -i '1a JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"' ${TOMCAT_HOME}/bin/catalina.sh && \
    wget --no-check-certificate -P ${TOMCAT_HOME}/webapps/ https://mirrors.tuna.tsinghua.edu.cn/jenkins/war/${JENKINS_EVERSION}/jenkins.war && \
    wget --no-check-certificate https://services.gradle.org/distributions/gradle-${GRADLE_EVERSION}-bin.zip  && \
    unzip gradle-${GRADLE_EVERSION}-bin.zip && \
    mv gradle-${GRADLE_EVERSION} ${GRADLE_HOME} && \
    rm -rf gradle-${GRADLE_EVERSION}-bin.zip && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV JAVA_HOME=/usr/local/jdk1.8.0_241 \
    CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib \
    PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$TOMCAT_HOME/bin:$GRADLE_HOME/bin:$PATH

WORKDIR ${TOMCAT_HOME}

EXPOSE 8080
CMD ["catalina.sh", "run"]