FROM centos:7.9.2009
MAINTAINER Cxs1103

COPY jdk-8u241-linux-x64.tar.gz /usr/local/
COPY apache-ant-1.10.11-bin.tar.gz /usr/local/
COPY apache-jmeter-5.4.3.tgz /usr/local/

RUN tar -zxf /usr/local/jdk-8u241-linux-x64.tar.gz -C /usr/local/ && \
    tar zxf /usr/local/apache-jmeter-5.4.3.tgz -C /usr/local/  && \
    tar zxf /usr/local/apache-ant-1.10.11-bin.tar.gz -C /usr/local/  && \
    rm -rf /usr/local/jdk-8u241-linux-x64.tar.gz /usr/local/apache-jmeter-5.4.3.tgz /usr/local/apache-ant-1.10.11-bin.tar.gz && \
    cp /usr/local/apache-jmeter-5.4.3/extras/ant-jmeter-1.1.1.jar /usr/local/apache-ant-1.10.11/lib/ && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV JAVA_HOME=/usr/local/jdk1.8.0_241 \
    ANT_HOME=/usr/local/apache-ant-1.10.11 \
    JMETER_HOME=/usr/local/apache-jmeter-5.4.3 \
    CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib \
    PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$JMETER_HOME/bin:$ANT_HOME/bin:$PATH