version: "3.0"

services:
  demo:
    build: #启动服务时先将build命令中指定Dockerfile打包成镜像。再运行该镜像
      context: demo # 指定上下文目录Dockerfile所在目录
      dockerfile: Dockerfile
    container_name: demo
    ports:
      - "8082:8081"
    networks:
      - test
    depends_on:
      - tomcat01

  tomcat01: # 服务名唯一
    container_name: tomcat01 #相当于有run的--name
    image: tomcat:8.5.56 # 使用那个镜像  相当于run image
    ports:  #用来完成host与容器的端口映射  相当于run -p
      - 8080:8080  # 外部端口:内部端口
    volumes:  #用来完成宿主机与容器中目录数据卷共享  相当于run -v
      # - /root/docker/webapps:/usr/local/tomcat/webapps #使用自定义路径映射
      - tomcatwebapps01:/usr/local/tomcat/webapps    #创建数据卷进行映射
    networks:   #代表当前服务使用的那个网桥   相当于run --net
      - test
    depends_on: #代表这个容器必须依赖哪些容器启动之后才可以启动
      - tomcat02  # 书写的是服务名
      - mysql
      - redis 
    healthcheck:
      test: ["CMD","curl","-f","http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  tomcat02:
    container_name: tomcat02
    image: tomcat:8.5.56
    ports:
      - 8081:8080
    volumes:
      # - /root/docker/webapps:/usr/local/tomcat/webapps
      - tomcatwebapps02:/usr/local/tomcat/webapps
    networks:
      - test
   # sysctrls:
   #   net.core.somaxconn: 1024
   #   net.ipv4.ecp_syncookies: 0
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  mysql:
    container_name: mysql
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql #mysql数据卷
      - mysqlconf:/etc/mysql  #mysql配置文件
    #environment:   # mysql 环境变量配置，可以用数组或字典两种方式
    #  - MYSQL_ROOT_PASSWORD=root  # 使用环境变量设置mysql密码
    env_file:
      - ./mysql.env
    networks:
      - test

  redis:
    container_name: redis
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data # redis数据卷
    networks:
      - test
    command: "redis-server --appendonly yes" # run 镜像之后用来覆盖容器内容默认命令

volumes:  # 声明上面服务所使用的自动创建的卷名
  tomcatwebapps01: #声明指令的卷名  compose自动创建该卷名但是会在之前加入项目名
    external:  #使用自定义卷名
      false     # true确定使用指定卷名   注意：一旦使用外部自定义卷名启动服务之前必须手动创建
  tomcatwebapps02:
  mysqldata:
  mysqlconf:
  redisdata:

networks:  # 定义服务到桥
  test:   # 定义上面的服务用到的网桥名称，默认创建就是bridge
    external:
      true   #使用外部指定的网桥  注意：网桥必须提前创建好，必须存在
