FROM centos:7.9.2009
MAINTAINER Cxs1103

COPY ./android-sdk/.android /root/.android
COPY ./android-sdk /usr/local/

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV JAVA_HOME=/usr/local/jdk1.8.0_241 \
    GRADLE_HOME=/usr/local/gradle-7.2 \
    ANDROID_HOME=/usr/local \
    CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib 

ENV PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$GRADLE_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platforms:$PATH

WORKDIR /usr/local
